[colors]
foreground = "#eeead9"
background = "#141414"

ansi = [
  "#31322c",
  "#ab1d22",
  "#2a6e3f",
  "#d6bc46",
  "#06436f",
  "#6c216d",
  "#108b96",
  "#ecebc2",
]
brights = [
  "#5c4f55",
  "#d24735",
  "#6a8d52",
  "#f2c867",
  "#106898",
  "#a6559d",
  "#87c0ca",
  "#f6f9e4",
]
